AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/BeginEndAlignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Naming/VariableNumber:
  EnforcedStyle: snake_case
