AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
Layout/EndOfLine:
  EnforcedStyle: lf
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false