default: &default
  lives_detect:
    delay: 5
    interval: 60
  lives_check:
    delay: 10
    interval: 60
  members_track:
    delay: 20
    interval: 3600

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default