default: &default
  lives_detect:
    youtube:
      - https://workername.username.workers.dev
    twitch:
      - worker: https://anotherworker.username.workers.dev
        proxy: http://example.com:1234
  lives_check:
    youtube:
      - https://youtube-live-check.yunzhe35p.workers.dev
  members_track:
    youtube:
      - https://youtube-live-check.yunzhe35p.workers.dev

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default