default: &default
  youtube:
    - https://workername.username.workers.dev
  bilibili:
    - https://anotherworker.username.workers.dev

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default