# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
youtube = Platform.find_or_create_by!(platform: 'youtube')
bilibili = Platform.find_or_create_by!(platform: 'bilibili')

tokinosora = Member.find_or_create_by!(name: 'ときのそら')
azki = Member.find_or_create_by!(name: 'AZKi')
robocosan = Member.find_or_create_by!(name: 'ロボ子さん')
sakuramiko = Member.find_or_create_by!(name: 'さくらみこ')
shirakamifubuki = Member.find_or_create_by!(name: '白上フブキ')
natsuiromatsuri = Member.find_or_create_by!(name: '夏色まつり')
yozoramel = Member.find_or_create_by!(name: '夜空メル')
akaihaato = Member.find_or_create_by!(name: '赤井はあと')
akirosenthal = Member.find_or_create_by!(name: 'アキ・ローゼンタール')
minatoaqua = Member.find_or_create_by!(name: '湊あくあ')
yuzukichoco = Member.find_or_create_by!(name: '癒月ちょこ')
nakiriayame = Member.find_or_create_by!(name: '百鬼あやめ')
murasakishion = Member.find_or_create_by!(name: '紫咲シオン')
oozorasubaru = Member.find_or_create_by!(name: '大空スバル')
ookamimio = Member.find_or_create_by!(name: '大神ミオ')
mekomataokayu = Member.find_or_create_by!(name: '猫又おかゆ')
inugamikorone = Member.find_or_create_by!(name: '戌神ころね')
shiranuiflare = Member.find_or_create_by!(name: '不知火フレア')
shiroganenoel = Member.find_or_create_by!(name: '白銀ノエル')
houshoumarine = Member.find_or_create_by!(name: '宝鐘マリン')
usadapekora = Member.find_or_create_by!(name: '兎田ぺこら')
uruharushia = Member.find_or_create_by!(name: '潤羽るしあ')
hoshimatisuisei = Member.find_or_create_by!(name: '星街すいせい')
amanekanata = Member.find_or_create_by!(name: '天音かなた')
kiryucoco = Member.find_or_create_by!(name: '桐生ココ')
tsunomakiwatame = Member.find_or_create_by!(name: '角巻わため')
tokoyamitowa = Member.find_or_create_by!(name: '常闇トワ')
himemoriluna = Member.find_or_create_by!(name: '姫森ルーナ')

tokinosora_y = Channel.find_or_create_by!(channel: 'UCp6993wxpyDPHUpavwDFqgg', platform: youtube, member: tokinosora)
azki_y = Channel.find_or_create_by!(channel: 'UC0TXe_LYZ4scaW2XMyi5_kw', platform: youtube, member: azki)
robocosan_y = Channel.find_or_create_by!(channel: 'UCDqI2jOz0weumE8s7paEk6g', platform: youtube, member: robocosan)
sakuramiko_y = Channel.find_or_create_by!(channel: 'UC-hM6YJuNYVAmUWxeIr9FeA', platform: youtube, member: sakuramiko)
shirakamifubuki_y = Channel.find_or_create_by!(channel: 'UCdn5BQ06XqgXoAxIhbqw5Rg', platform: youtube, member: shirakamifubuki)
natsuiromatsuri_y = Channel.find_or_create_by!(channel: 'UCQ0UDLQCjY0rmuxCDE38FGg', platform: youtube, member: natsuiromatsuri)
yozoramel_y = Channel.find_or_create_by!(channel: 'UCD8HOxPs4Xvsm8H0ZxXGiBw', platform: youtube, member: yozoramel)
akaihaato_y = Channel.find_or_create_by!(channel: 'UC1CfXB_kRs3C-zaeTG3oGyg', platform: youtube, member: akaihaato)
akirosenthal_y = Channel.find_or_create_by!(channel: 'UCFTLzh12_nrtzqBPsTCqenA', platform: youtube, member: akirosenthal)
minatoaqua_y = Channel.find_or_create_by!(channel: 'UC1opHUrw8rvnsadT-iGp7Cg', platform: youtube, member: minatoaqua)
yuzukichoco_y = Channel.find_or_create_by!(channel: 'UC1suqwovbL1kzsoaZgFZLKg', platform: youtube, member: yuzukichoco)
nakiriayame_y = Channel.find_or_create_by!(channel: 'UC7fk0CB07ly8oSl0aqKkqFg', platform: youtube, member: nakiriayame)
murasakishion_y = Channel.find_or_create_by!(channel: 'UCXTpFs_3PqI41qX2d9tL2Rw', platform: youtube, member: murasakishion)
oozorasubaru_y = Channel.find_or_create_by!(channel: 'UCvzGlP9oQwU--Y0r9id_jnA', platform: youtube, member: oozorasubaru)
ookamimio_y = Channel.find_or_create_by!(channel: 'UCp-5t9SrOQwXMU7iIjQfARg', platform: youtube, member: ookamimio)
mekomataokayu_y = Channel.find_or_create_by!(channel: 'UCvaTdHTWBGv3MKj3KVqJVCw', platform: youtube, member: mekomataokayu)
inugamikorone_y = Channel.find_or_create_by!(channel: 'UChAnqc_AY5_I3Px5dig3X1Q', platform: youtube, member: inugamikorone)
shiranuiflare_y = Channel.find_or_create_by!(channel: 'UCvInZx9h3jC2JzsIzoOebWg', platform: youtube, member: shiranuiflare)
shiroganenoel_y = Channel.find_or_create_by!(channel: 'UCdyqAaZDKHXg4Ahi7VENThQ', platform: youtube, member: shiroganenoel)
houshoumarine_y = Channel.find_or_create_by!(channel: 'UCCzUftO8KOVkV4wQG1vkUvg', platform: youtube, member: houshoumarine)
usadapekora_y = Channel.find_or_create_by!(channel: 'UC1DCedRgGHBdm81E1llLhOQ', platform: youtube, member: usadapekora)
uruharushia_y = Channel.find_or_create_by!(channel: 'UCl_gCybOJRIgOXw6Qb4qJzQ', platform: youtube, member: uruharushia)
hoshimatisuisei_y = Channel.find_or_create_by!(channel: 'UC5CwaMl1eIgY8h02uZw7u8A', platform: youtube, member: hoshimatisuisei)
amanekanata_y = Channel.find_or_create_by!(channel: 'UCZlDXzGoo7d44bwdNObFacg', platform: youtube, member: amanekanata)
kiryucoco_y = Channel.find_or_create_by!(channel: 'UCS9uQI-jC3DE0L4IpXyvr6w', platform: youtube, member: kiryucoco)
tsunomakiwatame_y = Channel.find_or_create_by!(channel: 'UCqm3BQLlJfvkTsX_hvm0UmA', platform: youtube, member: tsunomakiwatame)
tokoyamitowa_y = Channel.find_or_create_by!(channel: 'UC1uv2Oq6kNxgATlCiez59hw', platform: youtube, member: tokoyamitowa)
himemoriluna_y = Channel.find_or_create_by!(channel: 'UCa9Y57gfeY0Zro_noHRVrnw', platform: youtube, member: himemoriluna)
yuzukichoco_y_2 = Channel.find_or_create_by!(channel: 'UCp3tgHXw_HI0QMk1K8qh3gQ', platform: youtube, member: yuzukichoco)

tokinosora_b = Channel.find_or_create_by!(channel: '8899503', platform: bilibili, member: tokinosora)
azki_b = Channel.find_or_create_by!(channel: '21267062', platform: bilibili, member: azki)
robocosan_b = Channel.find_or_create_by!(channel: '4664126', platform: bilibili, member: robocosan)
sakuramiko_b = Channel.find_or_create_by!(channel: '21144047', platform: bilibili, member: sakuramiko)
shirakamifubuki_b = Channel.find_or_create_by!(channel: '11588230', platform: bilibili, member: shirakamifubuki)
natsuiromatsuri_b = Channel.find_or_create_by!(channel: '13946381', platform: bilibili, member: natsuiromatsuri)
yozoramel_b = Channel.find_or_create_by!(channel: '21131813', platform: bilibili, member: yozoramel)
akaihaato_b = Channel.find_or_create_by!(channel: '14275133', platform: bilibili, member: akaihaato)
akirosenthal_b = Channel.find_or_create_by!(channel: '21219990', platform: bilibili, member: akirosenthal)
minatoaqua_b = Channel.find_or_create_by!(channel: '14917277', platform: bilibili, member: minatoaqua)
yuzukichoco_b = Channel.find_or_create_by!(channel: '21107534', platform: bilibili, member: yuzukichoco)
nakiriayame_b = Channel.find_or_create_by!(channel: '21130785', platform: bilibili, member: nakiriayame)
murasakishion_b = Channel.find_or_create_by!(channel: '21132965', platform: bilibili, member: murasakishion)
oozorasubaru_b = Channel.find_or_create_by!(channel: '21129632', platform: bilibili, member: oozorasubaru)
ookamimio_b = Channel.find_or_create_by!(channel: '21133979', platform: bilibili, member: ookamimio)
mekomataokayu_b = Channel.find_or_create_by!(channel: '21420932', platform: bilibili, member: mekomataokayu)
inugamikorone_b = Channel.find_or_create_by!(channel: '21421141', platform: bilibili, member: inugamikorone)
shiranuiflare_b = Channel.find_or_create_by!(channel: '21572617', platform: bilibili, member: shiranuiflare)
shiroganenoel_b = Channel.find_or_create_by!(channel: '21583736', platform: bilibili, member: shiroganenoel)
houshoumarine_b = Channel.find_or_create_by!(channel: '21584153', platform: bilibili, member: houshoumarine)
usadapekora_b = Channel.find_or_create_by!(channel: '21560356', platform: bilibili, member: usadapekora)
uruharushia_b = Channel.find_or_create_by!(channel: '21545232', platform: bilibili, member: uruharushia)
hoshimatisuisei_b = Channel.find_or_create_by!(channel: '190577', platform: bilibili, member: hoshimatisuisei)
amanekanata_b = Channel.find_or_create_by!(channel: '21752681', platform: bilibili, member: amanekanata)
kiryucoco_b = Channel.find_or_create_by!(channel: '21752686', platform: bilibili, member: kiryucoco)
tsunomakiwatame_b = Channel.find_or_create_by!(channel: '21752694', platform: bilibili, member: tsunomakiwatame)
tokoyamitowa_b = Channel.find_or_create_by!(channel: '21752710', platform: bilibili, member: tokoyamitowa)
himemoriluna_b = Channel.find_or_create_by!(channel: '21752719', platform: bilibili, member: himemoriluna)
