# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
youtube = Platform.find_or_create_by!(platform: 'youtube')
bilibili = Platform.find_or_create_by!(platform: 'bilibili')

tokinosora = Member.find_or_create_by!(name: 'ときのそら')
azki = Member.find_or_create_by!(name: 'AZKi')
robocosan = Member.find_or_create_by!(name: 'ロボ子さん')
sakuramiko = Member.find_or_create_by!(name: 'さくらみこ')
shirakamifubuki = Member.find_or_create_by!(name: '白上フブキ')
natsuiromatsuri = Member.find_or_create_by!(name: '夏色まつり')
yozoramel = Member.find_or_create_by!(name: '夜空メル')
akaihaato = Member.find_or_create_by!(name: '赤井はあと')
akirosenthal = Member.find_or_create_by!(name: 'アキ・ローゼンタール')
minatoaqua = Member.find_or_create_by!(name: '湊あくあ')
yuzukichoco = Member.find_or_create_by!(name: '癒月ちょこ')
nakiriayame = Member.find_or_create_by!(name: '百鬼あやめ')
murasakishion = Member.find_or_create_by!(name: '紫咲シオン')
oozorasubaru = Member.find_or_create_by!(name: '大空スバル')
ookamimio = Member.find_or_create_by!(name: '大神ミオ')
mekomataokayu = Member.find_or_create_by!(name: '猫又おかゆ')
inugamikorone = Member.find_or_create_by!(name: '戌神ころね')
shiranuiflare = Member.find_or_create_by!(name: '不知火フレア')
shiroganenoel = Member.find_or_create_by!(name: '白銀ノエル')
houshoumarine = Member.find_or_create_by!(name: '宝鐘マリン')
usadapekora = Member.find_or_create_by!(name: '兎田ぺこら')
uruharushia = Member.find_or_create_by!(name: '潤羽るしあ')
hoshimatisuisei = Member.find_or_create_by!(name: '星街すいせい')
amanekanata = Member.find_or_create_by!(name: '天音かなた')
kiryucoco = Member.find_or_create_by!(name: '桐生ココ')
tsunomakiwatame = Member.find_or_create_by!(name: '角巻わため')
tokoyamitowa = Member.find_or_create_by!(name: '常闇トワ')
himemoriluna = Member.find_or_create_by!(name: '姫森ルーナ')

tokinosora.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l79dHleIBmBtLP2TfcmFpIJjmH7fa8tfG1qTKg=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#4075ff', color_sub: '#fc01b3')
azki.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJwDg8CoHtj7qnk1aj5h75lIWOaH-__JNzqNGA=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#f9002f', color_sub: '#58e1f1')
robocosan.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJzPUElg3_AunkFVflcyLEGybFmP3Txpg1c-AQ=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#d252ff', color_sub: '#fca5cf')
sakuramiko.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJztlxp1NvyEG3ULspVuGLwdoweCnhDsZDzgqA=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#ffa4cf', color_sub: '#f50f3e')
shirakamifubuki.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7-oeSvjxgdwMoDyT1LMH8nyqkWJCZH8MAOjzg=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#48e6ff', color_sub: '#ffffff')
natsuiromatsuri.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7_MTJEH9Kn-cVznPJPBt4v0BOkmd5btoSdz6Q=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#ff7709', color_sub: '#3be898')
yozoramel.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJw__74rAt8SKtuBzHDGXg7AlSXGjJ0aO1giMw=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#ffd200', color_sub: '#fd760a')
akaihaato.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7-ULNK73gTCGtPrM6elTCL-ValOSptM0YTXkQ=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#fe00ae', color_sub: '#f7002f')
akirosenthal.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7-MKGs8oe830HpPIlyQ3pNAVqUgqiMdSg8TwQ=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#8045ff', color_sub: '#ffa3cf')
minatoaqua.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJwHPp_TkvcWJyblt9XVYDjNSjrj6KdpQSCQNQ=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#d252ff', color_sub: '#63e5ff')
yuzukichoco.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l79rj4svlTtPimVkcxdUJS8VGt01u_mqZWZIbA=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#fb1fb7', color_sub: '#f9a8c9')
nakiriayame.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJyDhi8y6CDBgpb-yV0T-aiZc8oXwMG7NacqOg=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#f7002f', color_sub: '#ffffff')
murasakishion.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l79Wv6njnWc-lQDwczBQVLgBIRMD8PJ72ZIPLg=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#d252ff', color_sub: '#ffd246')
oozorasubaru.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJw9_oqF22fvOEqGj2rHC12PadwHN-NlFL4DeA=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#ffd52d', color_sub: '#58eaa3')
ookamimio.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJzFpyPB7LFGFq5DIX2x7pvIblA9Ksz99TrDYvOa5w=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#3be898', color_sub: '#f7002f')
mekomataokayu.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJxiB3oU3X4_wTHHAay43njgJgzw-2qKPeYIjDH2=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#d252ff', color_sub: '#4374ff')
inugamikorone.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJyL8gbKgJBHALWhWp56B6QTdNUPb03zwvT1uw=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#ffd200', color_sub: '#4de4ff')
shiranuiflare.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJwGmRMcFMvE1JW3v152HnrXfMQxbI_Dw92KH0-CpA=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#fc8328', color_sub: '#ffffff')
shiroganenoel.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJwBxPdKpbHq1LKbJb_HIj691WraJza8FWnYZw=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#ffffff', color_sub: '#4de4ff')
houshoumarine.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJxeNWA_oVxR5sKIs9hQotV_M9zS3NtgqB3tcw=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#f7002f', color_sub: '#ff811d')
usadapekora.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJyMxAFFr0_eQYgUQWkV6CWlx_t1NETncJygQA=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#4de4ff', color_sub: '#ff7f34')
uruharushia.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJxpi3N0NvZfBKKkEPPXx2U5xmQPNUT8AVOj1g=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#8045ff', color_sub: '#92f43f')
hoshimatisuisei.update!(avatar: 'https://yt3.ggpht.com/a/AATXAJwKuNhye0SEMSrtM5HUe5aVtKyxAvmdDlSpWw=s100-c-k-c0xffffffff-no-rj-mo', color_main: '#4074ff', color_sub: '#4de4ff')
amanekanata.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7_OdjohiBOVMZd0dHxZ1Jh1S1kJKGS0nYfNVg=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#509bea', color_sub: '#4de4ff')
kiryucoco.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7-UWVGytfW-cAiCvg8r2C_6Gk2SnqSkJP9Cqg=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#f38514', color_sub: '#4de4ff')
tsunomakiwatame.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l78pYNGWXckjVjmMsSz4iPeCzmWB2DHFW3lLdQ=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#f9afb2', color_sub: '#4de4ff')
tokoyamitowa.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7_MD5OqIfTp-JG-F5QSAiIIsprC8TrQpVhdvA=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#ba92ca', color_sub: '#4de4ff')
himemoriluna.update!(avatar: 'https://yt3.ggpht.com/a/AGF-l7-xWfYjQX1VHU2i1BuIap0Ba3tR3T6w4dcCkA=s88-c-k-c0xffffffff-no-rj-mo', color_main: '#f7abd5', color_sub: '#4de4ff')

tokinosora_y = Channel.find_or_create_by!(channel: 'UCp6993wxpyDPHUpavwDFqgg', platform: youtube, member: tokinosora)
azki_y = Channel.find_or_create_by!(channel: 'UC0TXe_LYZ4scaW2XMyi5_kw', platform: youtube, member: azki)
robocosan_y = Channel.find_or_create_by!(channel: 'UCDqI2jOz0weumE8s7paEk6g', platform: youtube, member: robocosan)
sakuramiko_y = Channel.find_or_create_by!(channel: 'UC-hM6YJuNYVAmUWxeIr9FeA', platform: youtube, member: sakuramiko)
shirakamifubuki_y = Channel.find_or_create_by!(channel: 'UCdn5BQ06XqgXoAxIhbqw5Rg', platform: youtube, member: shirakamifubuki)
natsuiromatsuri_y = Channel.find_or_create_by!(channel: 'UCQ0UDLQCjY0rmuxCDE38FGg', platform: youtube, member: natsuiromatsuri)
yozoramel_y = Channel.find_or_create_by!(channel: 'UCD8HOxPs4Xvsm8H0ZxXGiBw', platform: youtube, member: yozoramel)
akaihaato_y = Channel.find_or_create_by!(channel: 'UC1CfXB_kRs3C-zaeTG3oGyg', platform: youtube, member: akaihaato)
akirosenthal_y = Channel.find_or_create_by!(channel: 'UCFTLzh12_nrtzqBPsTCqenA', platform: youtube, member: akirosenthal)
minatoaqua_y = Channel.find_or_create_by!(channel: 'UC1opHUrw8rvnsadT-iGp7Cg', platform: youtube, member: minatoaqua)
yuzukichoco_y = Channel.find_or_create_by!(channel: 'UC1suqwovbL1kzsoaZgFZLKg', platform: youtube, member: yuzukichoco)
nakiriayame_y = Channel.find_or_create_by!(channel: 'UC7fk0CB07ly8oSl0aqKkqFg', platform: youtube, member: nakiriayame)
murasakishion_y = Channel.find_or_create_by!(channel: 'UCXTpFs_3PqI41qX2d9tL2Rw', platform: youtube, member: murasakishion)
oozorasubaru_y = Channel.find_or_create_by!(channel: 'UCvzGlP9oQwU--Y0r9id_jnA', platform: youtube, member: oozorasubaru)
ookamimio_y = Channel.find_or_create_by!(channel: 'UCp-5t9SrOQwXMU7iIjQfARg', platform: youtube, member: ookamimio)
mekomataokayu_y = Channel.find_or_create_by!(channel: 'UCvaTdHTWBGv3MKj3KVqJVCw', platform: youtube, member: mekomataokayu)
inugamikorone_y = Channel.find_or_create_by!(channel: 'UChAnqc_AY5_I3Px5dig3X1Q', platform: youtube, member: inugamikorone)
shiranuiflare_y = Channel.find_or_create_by!(channel: 'UCvInZx9h3jC2JzsIzoOebWg', platform: youtube, member: shiranuiflare)
shiroganenoel_y = Channel.find_or_create_by!(channel: 'UCdyqAaZDKHXg4Ahi7VENThQ', platform: youtube, member: shiroganenoel)
houshoumarine_y = Channel.find_or_create_by!(channel: 'UCCzUftO8KOVkV4wQG1vkUvg', platform: youtube, member: houshoumarine)
usadapekora_y = Channel.find_or_create_by!(channel: 'UC1DCedRgGHBdm81E1llLhOQ', platform: youtube, member: usadapekora)
uruharushia_y = Channel.find_or_create_by!(channel: 'UCl_gCybOJRIgOXw6Qb4qJzQ', platform: youtube, member: uruharushia)
hoshimatisuisei_y = Channel.find_or_create_by!(channel: 'UC5CwaMl1eIgY8h02uZw7u8A', platform: youtube, member: hoshimatisuisei)
amanekanata_y = Channel.find_or_create_by!(channel: 'UCZlDXzGoo7d44bwdNObFacg', platform: youtube, member: amanekanata)
kiryucoco_y = Channel.find_or_create_by!(channel: 'UCS9uQI-jC3DE0L4IpXyvr6w', platform: youtube, member: kiryucoco)
tsunomakiwatame_y = Channel.find_or_create_by!(channel: 'UCqm3BQLlJfvkTsX_hvm0UmA', platform: youtube, member: tsunomakiwatame)
tokoyamitowa_y = Channel.find_or_create_by!(channel: 'UC1uv2Oq6kNxgATlCiez59hw', platform: youtube, member: tokoyamitowa)
himemoriluna_y = Channel.find_or_create_by!(channel: 'UCa9Y57gfeY0Zro_noHRVrnw', platform: youtube, member: himemoriluna)
yuzukichoco_y_2 = Channel.find_or_create_by!(channel: 'UCp3tgHXw_HI0QMk1K8qh3gQ', platform: youtube, member: yuzukichoco)

tokinosora_b = Channel.find_or_create_by!(channel: '8899503', platform: bilibili, member: tokinosora)
azki_b = Channel.find_or_create_by!(channel: '21267062', platform: bilibili, member: azki)
robocosan_b = Channel.find_or_create_by!(channel: '4664126', platform: bilibili, member: robocosan)
sakuramiko_b = Channel.find_or_create_by!(channel: '21144047', platform: bilibili, member: sakuramiko)
shirakamifubuki_b = Channel.find_or_create_by!(channel: '11588230', platform: bilibili, member: shirakamifubuki)
natsuiromatsuri_b = Channel.find_or_create_by!(channel: '13946381', platform: bilibili, member: natsuiromatsuri)
yozoramel_b = Channel.find_or_create_by!(channel: '21131813', platform: bilibili, member: yozoramel)
akaihaato_b = Channel.find_or_create_by!(channel: '14275133', platform: bilibili, member: akaihaato)
akirosenthal_b = Channel.find_or_create_by!(channel: '21219990', platform: bilibili, member: akirosenthal)
minatoaqua_b = Channel.find_or_create_by!(channel: '14917277', platform: bilibili, member: minatoaqua)
yuzukichoco_b = Channel.find_or_create_by!(channel: '21107534', platform: bilibili, member: yuzukichoco)
nakiriayame_b = Channel.find_or_create_by!(channel: '21130785', platform: bilibili, member: nakiriayame)
murasakishion_b = Channel.find_or_create_by!(channel: '21132965', platform: bilibili, member: murasakishion)
oozorasubaru_b = Channel.find_or_create_by!(channel: '21129632', platform: bilibili, member: oozorasubaru)
ookamimio_b = Channel.find_or_create_by!(channel: '21133979', platform: bilibili, member: ookamimio)
mekomataokayu_b = Channel.find_or_create_by!(channel: '21420932', platform: bilibili, member: mekomataokayu)
inugamikorone_b = Channel.find_or_create_by!(channel: '21421141', platform: bilibili, member: inugamikorone)
shiranuiflare_b = Channel.find_or_create_by!(channel: '21572617', platform: bilibili, member: shiranuiflare)
shiroganenoel_b = Channel.find_or_create_by!(channel: '21583736', platform: bilibili, member: shiroganenoel)
houshoumarine_b = Channel.find_or_create_by!(channel: '21584153', platform: bilibili, member: houshoumarine)
usadapekora_b = Channel.find_or_create_by!(channel: '21560356', platform: bilibili, member: usadapekora)
uruharushia_b = Channel.find_or_create_by!(channel: '21545232', platform: bilibili, member: uruharushia)
hoshimatisuisei_b = Channel.find_or_create_by!(channel: '190577', platform: bilibili, member: hoshimatisuisei)
amanekanata_b = Channel.find_or_create_by!(channel: '21752681', platform: bilibili, member: amanekanata)
kiryucoco_b = Channel.find_or_create_by!(channel: '21752686', platform: bilibili, member: kiryucoco)
tsunomakiwatame_b = Channel.find_or_create_by!(channel: '21752694', platform: bilibili, member: tsunomakiwatame)
tokoyamitowa_b = Channel.find_or_create_by!(channel: '21752710', platform: bilibili, member: tokoyamitowa)
himemoriluna_b = Channel.find_or_create_by!(channel: '21752719', platform: bilibili, member: himemoriluna)
