# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
youtube = Platform.create(platform: 'youtube')
bilibili = Platform.create(platform: 'bilibili')

tokinosora = Member.create(name: 'ときのそら')
azki = Member.create(name: 'AZKi')
robocosan = Member.create(name: 'ロボ子さん')
sakuramiko = Member.create(name: 'さくらみこ')
shirakamifubuki = Member.create(name: '白上フブキ')
natsuiromatsuri = Member.create(name: '夏色まつり')
yozoramel = Member.create(name: '夜空メル')
akaihaato = Member.create(name: '赤井はあと')
akirosenthal = Member.create(name: 'アキ・ローゼンタール')
minatoaqua = Member.create(name: '湊あくあ')
yuzukichoco = Member.create(name: '癒月ちょこ')
nakiriayame = Member.create(name: '百鬼あやめ')
murasakishion = Member.create(name: '紫咲シオン')
oozorasubaru = Member.create(name: '大空スバル')
ookamimio = Member.create(name: '大神ミオ')
mekomataokayu = Member.create(name: '猫又おかゆ')
inugamikorone = Member.create(name: '戌神ころね')
shiranuiflare = Member.create(name: '不知火フレア')
shiroganenoel = Member.create(name: '白銀ノエル')
houshoumarine = Member.create(name: '宝鐘マリン')
usadapekora = Member.create(name: '兎田ぺこら')
uruharushia = Member.create(name: '潤羽るしあ')
hoshimatisuisei = Member.create(name: '星街すいせい')
amanekanata = Member.create(name: '天音かなた')
kiryucoco = Member.create(name: '桐生ココ')
tsunomakiwatame = Member.create(name: '角巻わため')
tokoyamitowa = Member.create(name: '常闇トワ')
himemoriluna = Member.create(name: '姫森ルーナ')

tokinosora_y = Channel.create(channel: 'UCp6993wxpyDPHUpavwDFqgg', platform: youtube, member: tokinosora)
azki_y = Channel.create(channel: 'UC0TXe_LYZ4scaW2XMyi5_kw', platform: youtube, member: azki)
robocosan_y = Channel.create(channel: 'UCDqI2jOz0weumE8s7paEk6g', platform: youtube, member: robocosan)
sakuramiko_y = Channel.create(channel: 'UC-hM6YJuNYVAmUWxeIr9FeA', platform: youtube, member: sakuramiko)
shirakamifubuki_y = Channel.create(channel: 'UCdn5BQ06XqgXoAxIhbqw5Rg', platform: youtube, member: shirakamifubuki)
natsuiromatsuri_y = Channel.create(channel: 'UCQ0UDLQCjY0rmuxCDE38FGg', platform: youtube, member: natsuiromatsuri)
yozoramel_y = Channel.create(channel: 'UCD8HOxPs4Xvsm8H0ZxXGiBw', platform: youtube, member: yozoramel)
akaihaato_y = Channel.create(channel: 'UC1CfXB_kRs3C-zaeTG3oGyg', platform: youtube, member: akaihaato)
akirosenthal_y = Channel.create(channel: 'UCFTLzh12_nrtzqBPsTCqenA', platform: youtube, member: akirosenthal)
minatoaqua_y = Channel.create(channel: 'UC1opHUrw8rvnsadT-iGp7Cg', platform: youtube, member: minatoaqua)
yuzukichoco_y = Channel.create(channel: 'UC1suqwovbL1kzsoaZgFZLKg', platform: youtube, member: yuzukichoco)
nakiriayame_y = Channel.create(channel: 'UC7fk0CB07ly8oSl0aqKkqFg', platform: youtube, member: nakiriayame)
murasakishion_y = Channel.create(channel: 'UCXTpFs_3PqI41qX2d9tL2Rw', platform: youtube, member: murasakishion)
oozorasubaru_y = Channel.create(channel: 'UCvzGlP9oQwU--Y0r9id_jnA', platform: youtube, member: oozorasubaru)
ookamimio_y = Channel.create(channel: 'UCp-5t9SrOQwXMU7iIjQfARg', platform: youtube, member: ookamimio)
mekomataokayu_y = Channel.create(channel: 'UCvaTdHTWBGv3MKj3KVqJVCw', platform: youtube, member: mekomataokayu)
inugamikorone_y = Channel.create(channel: 'UChAnqc_AY5_I3Px5dig3X1Q', platform: youtube, member: inugamikorone)
shiranuiflare_y = Channel.create(channel: 'UCvInZx9h3jC2JzsIzoOebWg', platform: youtube, member: shiranuiflare)
shiroganenoel_y = Channel.create(channel: 'UCdyqAaZDKHXg4Ahi7VENThQ', platform: youtube, member: shiroganenoel)
houshoumarine_y = Channel.create(channel: 'UCCzUftO8KOVkV4wQG1vkUvg', platform: youtube, member: houshoumarine)
usadapekora_y = Channel.create(channel: 'UC1DCedRgGHBdm81E1llLhOQ', platform: youtube, member: usadapekora)
uruharushia_y = Channel.create(channel: 'UCl_gCybOJRIgOXw6Qb4qJzQ', platform: youtube, member: uruharushia)
hoshimatisuisei_y = Channel.create(channel: 'UC5CwaMl1eIgY8h02uZw7u8A', platform: youtube, member: hoshimatisuisei)
amanekanata_y = Channel.create(channel: 'UCZlDXzGoo7d44bwdNObFacg', platform: youtube, member: amanekanata)
kiryucoco_y = Channel.create(channel: 'UCS9uQI-jC3DE0L4IpXyvr6w', platform: youtube, member: kiryucoco)
tsunomakiwatame_y = Channel.create(channel: 'UCqm3BQLlJfvkTsX_hvm0UmA', platform: youtube, member: tsunomakiwatame)
tokoyamitowa_y = Channel.create(channel: 'UC1uv2Oq6kNxgATlCiez59hw', platform: youtube, member: tokoyamitowa)
himemoriluna_y = Channel.create(channel: 'UCa9Y57gfeY0Zro_noHRVrnw', platform: youtube, member: himemoriluna)
yuzukichoco_y_2 = Channel.create(channel: 'UCp3tgHXw_HI0QMk1K8qh3gQ', platform: youtube, member: yuzukichoco)
